'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=192.168.10.10:30015;UserName=SYSTEM;Password=Tekno2020.*")>  _
        Public Property conexionDBHANA() As String
            Get
                Return CType(Me("conexionDBHANA"),String)
            End Get
            Set
                Me("conexionDBHANA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SYSTEM")>  _
        Public Property UsuarioHANA() As String
            Get
                Return CType(Me("UsuarioHANA"),String)
            End Get
            Set
                Me("UsuarioHANA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tekno2020.*")>  _
        Public Property PasswordHANA() As String
            Get
                Return CType(Me("PasswordHANA"),String)
            End Get
            Set
                Me("PasswordHANA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.10.10:30015")>  _
        Public Property ServidorHANA() As String
            Get
                Return CType(Me("ServidorHANA"),String)
            End Get
            Set
                Me("ServidorHANA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30015")>  _
        Public Property PuertoServidor() As String
            Get
                Return CType(Me("PuertoServidor"),String)
            End Get
            Set
                Me("PuertoServidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("manager")>  _
        Public Property UsuarioSAP() As String
            Get
                Return CType(Me("UsuarioSAP"),String)
            End Get
            Set
                Me("UsuarioSAP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tekno2015.")>  _
        Public Property PasswordSAP() As String
            Get
                Return CType(Me("PasswordSAP"),String)
            End Get
            Set
                Me("PasswordSAP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property PuertoSL() As String
            Get
                Return CType(Me("PuertoSL"),String)
            End Get
            Set
                Me("PuertoSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property Meses() As String
            Get
                Return CType(Me("Meses"),String)
            End Get
            Set
                Me("Meses") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("testdesarrollosdescon@gmail.com")>  _
        Public Property UsuarioCorreo() As String
            Get
                Return CType(Me("UsuarioCorreo"),String)
            End Get
            Set
                Me("UsuarioCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Descon2020")>  _
        Public Property PasswordCorreo() As String
            Get
                Return CType(Me("PasswordCorreo"),String)
            End Get
            Set
                Me("PasswordCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property ServidorCorreo() As String
            Get
                Return CType(Me("ServidorCorreo"),String)
            End Get
            Set
                Me("ServidorCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UtilizarSSL() As Boolean
            Get
                Return CType(Me("UtilizarSSL"),Boolean)
            End Get
            Set
                Me("UtilizarSSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("angelitce@gmail.com")>  _
        Public Property CorreoTest() As String
            Get
                Return CType(Me("CorreoTest"),String)
            End Get
            Set
                Me("CorreoTest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("84")>  _
        Public Property NumPropietario() As String
            Get
                Return CType(Me("NumPropietario"),String)
            End Get
            Set
                Me("NumPropietario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dpaniaguasgs@gmail.com")>  _
        Public Property CorreoBitacora() As String
            Get
                Return CType(Me("CorreoBitacora"),String)
            End Get
            Set
                Me("CorreoBitacora") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0")>  _
        Public Property RangoRojoMin() As String
            Get
                Return CType(Me("RangoRojoMin"),String)
            End Get
            Set
                Me("RangoRojoMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.2")>  _
        Public Property RangoRojoMax() As String
            Get
                Return CType(Me("RangoRojoMax"),String)
            End Get
            Set
                Me("RangoRojoMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.3")>  _
        Public Property RangoAmarilloMin() As String
            Get
                Return CType(Me("RangoAmarilloMin"),String)
            End Get
            Set
                Me("RangoAmarilloMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.6")>  _
        Public Property RangoAmarilloMax() As String
            Get
                Return CType(Me("RangoAmarilloMax"),String)
            End Get
            Set
                Me("RangoAmarilloMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.7")>  _
        Public Property RangoVerdeMin() As String
            Get
                Return CType(Me("RangoVerdeMin"),String)
            End Get
            Set
                Me("RangoVerdeMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.9")>  _
        Public Property RangoVerdeMax() As String
            Get
                Return CType(Me("RangoVerdeMax"),String)
            End Get
            Set
                Me("RangoVerdeMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enviamos el siguiente correo como prueba de funcionalidad del mismo, quedando ate"& _ 
            "ntos a sus comentarios y agradeciendo su atención")>  _
        Public Property CuerpoCorreo() As String
            Get
                Return CType(Me("CuerpoCorreo"),String)
            End Get
            Set
                Me("CuerpoCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pedido TeknoStep")>  _
        Public Property AsuntoCorreo() As String
            Get
                Return CType(Me("AsuntoCorreo"),String)
            End Get
            Set
                Me("AsuntoCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Buen dia")>  _
        Public Property SaludoCorreo() As String
            Get
                Return CType(Me("SaludoCorreo"),String)
            End Get
            Set
                Me("SaludoCorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.10.10:40000")>  _
        Public Property Licencia() As String
            Get
                Return CType(Me("Licencia"),String)
            End Get
            Set
                Me("Licencia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TEKNOSTEP_PROD")>  _
        Public Property Empresa() As String
            Get
                Return CType(Me("Empresa"),String)
            End Get
            Set
                Me("Empresa") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.APP_TEKNO.My.MySettings
            Get
                Return Global.APP_TEKNO.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
